In [1]:
import pandas as pd 
import numpy as np

In [2]:
name = pd.read_csv('D:/Study/MSIT/2nd Year/DataScience_2019501007/Data Analytics and Data Visualisation/Task - 1/IMDB Data/name_basics.tsv', sep = "\t", header = 0)
basics = pd.read_csv('D:/Study/MSIT/2nd Year/DataScience_2019501007/Data Analytics and Data Visualisation/Task - 1/IMDB Data/title_basics.tsv', sep = "\t", header = 0)
ratings = pd.read_csv('D:/Study/MSIT/2nd Year/DataScience_2019501007/Data Analytics and Data Visualisation/Task - 1/IMDB Data/title_ratings.tsv', sep = "\t", header = 0)
# akas = pd.read_csv('D:/Study/MSIT/2nd Year/DataScience_2019501007/Data Analytics and Data Visualisation/Task - 1/IMDB Data/title_akas.tsv', sep = "\t", header = 0)
# crew = pd.read_csv('D:/Study/MSIT/2nd Year/DataScience_2019501007/Data Analytics and Data Visualisation/Task - 1/IMDB Data/title_crew.tsv', sep = "\t", header = 0)
# episode = pd.read_csv('D:/Study/MSIT/2nd Year/DataScience_2019501007/Data Analytics and Data Visualisation/Task - 1/IMDB Data/title_episode.tsv', sep = "\t", header = 0)
# principals = pd.read_csv('D:/Study/MSIT/2nd Year/DataScience_2019501007/Data Analytics and Data Visualisation/Task - 1/IMDB Data/title_principals.tsv', sep = "\t", header = 0)

C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
temp_basics = basics[basics["startYear"] != "\\N"]
temp_basics = temp_basics.astype({"startYear":"int"})
print(temp_basics.dtypes)

tconst            object
titleType         object
primaryTitle      object
originalTitle     object
isAdult           object
startYear          int32
endYear           object
runtimeMinutes    object
genres            object
dtype: object

In [4]:
sol = pd.merge(temp_basics, ratings, on = "tconst")
print(sol.head())

      tconst titleType            primaryTitle           originalTitle  \
0  tt0000001     short              Carmencita              Carmencita
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens
2  tt0000003     short          Pauvre Pierrot          Pauvre Pierrot
3  tt0000004     short             Un bon bock             Un bon bock
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene

  isAdult  startYear endYear runtimeMinutes                    genres  \
0       0       1894      \N              1         Documentary,Short
1       0       1892      \N              5           Animation,Short
2       0       1892      \N              4  Animation,Comedy,Romance
3       0       1892      \N             12           Animation,Short
4       0       1893      \N              1              Comedy,Short

   averageRating  numVotes
0            5.7      1669
1            6.1       207
2            6.5      1392
3            6.2       123
4            6.2      2181

# To Find the 20 most popular movies with a rank more than 8.0

In [5]:
temp_result = sol[(sol['averageRating'] > 8.0) & (sol["titleType"] == 'movie')]
result = temp_result.sort_values(by = 'numVotes', ascending = False)
result.head(20)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
81773,tt0111161,movie,The Shawshank Redemption,The Shawshank Redemption,0,1994,\N,142,Drama,9.3,2326344
246038,tt0468569,movie,The Dark Knight,The Dark Knight,0,2008,\N,152,"Action,Crime,Drama",9.0,2288140
582013,tt1375666,movie,Inception,Inception,0,2010,\N,148,"Action,Adventure,Sci-Fi",8.8,2051750
98054,tt0137523,movie,Fight Club,Fight Club,0,1999,\N,139,Drama,8.8,1842531
81557,tt0110912,movie,Pulp Fiction,Pulp Fiction,0,1994,\N,154,"Crime,Drama",8.9,1814425
80684,tt0109830,movie,Forrest Gump,Forrest Gump,0,1994,\N,142,"Drama,Romance",8.8,1795075
95969,tt0133093,movie,The Matrix,The Matrix,0,1999,\N,136,"Action,Sci-Fi",8.7,1664961
89544,tt0120737,movie,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the Ring,0,2001,\N,178,"Action,Adventure,Drama",8.8,1649550
112866,tt0167260,movie,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,0,2003,\N,201,"Action,Adventure,Drama",8.9,1632805
45695,tt0068646,movie,The Godfather,The Godfather,0,1972,\N,175,"Crime,Drama",9.2,1607349
574443,tt1345836,movie,The Dark Knight Rises,The Dark Knight Rises,0,2012,\N,164,"Action,Adventure",8.4,1507477
387558,tt0816692,movie,Interstellar,Interstellar,0,2014,\N,169,"Adventure,Drama,Sci-Fi",8.6,1496586
112867,tt0167261,movie,The Lord of the Rings: The Two Towers,The Lord of the Rings: The Two Towers,0,2002,\N,179,"Action,Adventure,Drama",8.7,1476251
84325,tt0114369,movie,Se7en,Se7en,0,1995,\N,127,"Crime,Drama,Mystery",8.6,1434119
666609,tt1853728,movie,Django Unchained,Django Unchained,0,2012,\N,165,"Drama,Western",8.4,1347347
115287,tt0172495,movie,Gladiator,Gladiator,0,2000,\N,155,"Action,Adventure,Drama",8.5,1333117
206365,tt0372784,movie,Batman Begins,Batman Begins,0,2005,\N,140,"Action,Adventure",8.2,1300916
74992,tt0102926,movie,The Silence of the Lambs,The Silence of the Lambs,0,1991,\N,118,"Crime,Drama,Thriller",8.6,1261810
201320,tt0361748,movie,Inglourious Basterds,Inglourious Basterds,0,2009,\N,153,"Adventure,Drama,War",8.3,1257816
89606,tt0120815,movie,Saving Private Ryan,Saving Private Ryan,0,1998,\N,169,"Drama,War",8.6,1227548

# To find the 20 best rated movies with over 40,000 votes in the 2000s (year >= 2000)

In [6]:
rated_movies = sol[(sol["numVotes"] >= 40000) & (sol["startYear"] >= 2000) & (sol["titleType"] == 'movie')]
res = rated_movies.sort_values(by = 'averageRating', ascending = False)
res.head(20)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
752672,tt2592910,movie,CM101MMXI Fundamentals,CM101MMXI Fundamentals,0,2013,\N,139,"Comedy,Documentary",9.2,43813
246038,tt0468569,movie,The Dark Knight,The Dark Knight,0,2008,\N,152,"Action,Crime,Drama",9.0,2288140
112866,tt0167260,movie,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,0,2003,\N,201,"Action,Adventure,Drama",8.9,1632805
582013,tt1375666,movie,Inception,Inception,0,2010,\N,148,"Action,Adventure,Sci-Fi",8.8,2051750
940296,tt5813916,movie,The Mountain II,Dag II,0,2016,\N,135,"Action,Drama,War",8.8,104744
89544,tt0120737,movie,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the Ring,0,2001,\N,178,"Action,Adventure,Drama",8.8,1649550
445593,tt10189514,movie,Soorarai Pottru,Soorarai Pottru,0,2020,\N,153,Drama,8.7,51610
112867,tt0167261,movie,The Lord of the Rings: The Two Towers,The Lord of the Rings: The Two Towers,0,2002,\N,179,"Action,Adventure,Drama",8.7,1476251
990094,tt6751668,movie,Parasite,Gisaengchung,0,2019,\N,132,"Comedy,Drama,Thriller",8.6,530801
183922,tt0317248,movie,City of God,Cidade de Deus,0,2002,\N,130,"Crime,Drama",8.6,696002
149309,tt0245429,movie,Spirited Away,Sen to Chihiro no kamikakushi,0,2001,\N,125,"Adventure,Animation,Family",8.6,644957
1063691,tt8503618,movie,Hamilton,Hamilton,0,2020,\N,160,"Biography,Drama,History",8.6,51526
387558,tt0816692,movie,Interstellar,Interstellar,0,2014,\N,169,"Adventure,Drama,Sci-Fi",8.6,1496586
636259,tt1675434,movie,The Intouchables,Intouchables,0,2011,\N,112,"Biography,Comedy,Drama",8.5,753012
152941,tt0253474,movie,The Pianist,The Pianist,0,2002,\N,150,"Biography,Drama,Music",8.5,724139
115287,tt0172495,movie,Gladiator,Gladiator,0,2000,\N,155,"Action,Adventure,Drama",8.5,1333117
752115,tt2582802,movie,Whiplash,Whiplash,0,2014,\N,106,"Drama,Music",8.5,710559
251928,tt0482571,movie,The Prestige,The Prestige,0,2006,\N,130,"Drama,Mystery,Sci-Fi",8.5,1181694
590882,tt1424432,movie,Senna,Senna,0,2010,\N,106,"Biography,Documentary,Sport",8.5,63861
221907,tt0407887,movie,The Departed,The Departed,0,2006,\N,151,"Crime,Drama,Thriller",8.5,1181716